package io.smithycpp.codegen;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

import org.junit.jupiter.api.Test;
import software.amazon.smithy.build.MockManifest;

/**
 * The generated BUILD.bazel is the one artifact issue #48 flagged as pinned by goldens alone: the
 * protocol conformance suites never load it. These tests assert the target set per mode and the
 * knobs that control emission.
 */
class BuildFileGeneratorTest {

  private static final String MODEL =
      """
      $version: "2.0"
      namespace test.build
      use smithy.cpp.protocols#jsonRpc2

      @jsonRpc2
      service Svc { version: "1", operations: [Op] }
      operation Op { input := { name: String } }
      """;

  private static MockManifest generate(String mode) {
    return generate(MODEL, mode);
  }

  private static MockManifest generate(String modelText, String mode) {
    return PluginTestHarness.generate(
        modelText,
        "test.build#Svc",
        "test::build",
        b -> b.withMember("runtimeTarget", "//runtime:core").withMember("mode", mode));
  }

  @Test
  void bothModeEmitsTypesSerdeClientAndServerTargets() {
    String build = generate("both").expectFileString("/BUILD.bazel");
    assertTrue(build.contains("name = \"types\""), build);
    assertTrue(build.contains("name = \"serde\""), build);
    assertTrue(build.contains("name = \"client\""), build);
    assertTrue(build.contains("name = \"server\""), build);
    assertTrue(build.contains("# Code generated by opal-cpp (cpp-codegen). DO NOT EDIT."));
    assertTrue(build.contains("load(\"@rules_cc//cc:defs.bzl\", \"cc_library\")"), build);
  }

  @Test
  void clientModeOmitsTheServerTarget() {
    String build = generate("client").expectFileString("/BUILD.bazel");
    assertTrue(build.contains("name = \"client\""), build);
    assertFalse(build.contains("name = \"server\""), build);
  }

  @Test
  void typesModeEmitsOnlyTheTypesTarget() {
    String build = generate("types").expectFileString("/BUILD.bazel");
    assertTrue(build.contains("name = \"types\""), build);
    assertFalse(build.contains("name = \"client\""), build);
    assertFalse(build.contains("name = \"server\""), build);
  }

  @Test
  void runtimeDepsPointAtTheConfiguredTarget() {
    String build = generate("both").expectFileString("/BUILD.bazel");
    assertTrue(build.contains("\"//runtime:core\""), build);
    // The consumer default is the external-repo spelling.
    String external =
        PluginTestHarness.generate(MODEL, "test.build#Svc", "test::build")
            .expectFileString("/BUILD.bazel");
    assertTrue(external.contains("\"@opal_cpp//runtime:core\""), external);
  }

  @Test
  void emitBuildFileFalseSuppressesTheFile() {
    MockManifest manifest =
        PluginTestHarness.generate(
            MODEL, "test.build#Svc", "test::build", b -> b.withMember("emitBuildFile", false));
    assertFalse(manifest.hasFile("/BUILD.bazel"), "emitBuildFile=false must suppress BUILD");
    assertTrue(manifest.hasFile("/include/test/build/types.h"));
  }

  @Test
  void gzipCompressionLinksTheCompressionTarget() {
    // The BUILD dep keys on ProtocolSupport.gzipCompressed, not on
    // @requestCompression's mere presence. The negative direction is
    // untestable through a real model — Smithy's RequestCompressionTrait
    // validator rejects every encoding except gzip at assembly — so the
    // predicate's non-gzip arm is pinned by ProtocolSupportTest instead.
    String compressed =
        """
        $version: "2.0"
        namespace test.build
        use smithy.cpp.protocols#jsonRpc2

        @jsonRpc2
        service Svc { version: "1", operations: [Op] }

        @requestCompression(encodings: ["gzip"])
        operation Op { input := { data: String } }
        """;
    String build = generate(compressed, "both").expectFileString("/BUILD.bazel");
    assertTrue(build.contains(":compression"), build);
    // And the base model (no compression anywhere) must not link it.
    String plain = generate("both").expectFileString("/BUILD.bazel");
    assertFalse(plain.contains(":compression"), plain);
  }

  @Test
  void compressionLinkageIsScopedToTheServiceClosure() {
    // Multi-service model (like roundtrip): a sibling service's compressed
    // operation must not drag :compression into THIS service's BUILD.
    String model =
        """
        $version: "2.0"
        namespace test.build
        use smithy.cpp.protocols#jsonRpc2

        @jsonRpc2
        service Plain { version: "1", operations: [Op] }
        operation Op { input := { name: String } }

        @jsonRpc2
        service Compressed { version: "1", operations: [Zip] }

        @requestCompression(encodings: ["gzip"])
        operation Zip { input := { data: String } }
        """;
    String build =
        PluginTestHarness.generate(model, "test.build#Plain", "test::build")
            .expectFileString("/BUILD.bazel");
    assertFalse(build.contains(":compression"), build);
  }
}
