package io.smithycpp.codegen;

import java.util.Set;
import java.util.TreeSet;
import software.amazon.smithy.codegen.core.Symbol;
import software.amazon.smithy.codegen.core.SymbolWriter;

/**
 * Writer for one generated C++ file. Collects {@code #include}s while the body is written, renders
 * them sorted (angle includes first, then quoted) after the file header, and wraps the body in the
 * module's namespace. Output is byte deterministic.
 */
public final class CppWriter extends SymbolWriter<CppWriter, CppWriter.IncludeContainer> {

  private final String filename;
  private final String cppNamespace;
  private CppWriter epilogue;

  public CppWriter(String filename, String cppNamespace) {
    this(new IncludeContainer(), filename, cppNamespace);
  }

  private CppWriter(IncludeContainer includes, String filename, String cppNamespace) {
    super(includes);
    this.filename = filename;
    this.cppNamespace = cppNamespace;
    trimTrailingSpaces();
    setIndentText("  ");
  }

  /** The C++ namespace this file's body is wrapped in. */
  public String cppNamespace() {
    return cppNamespace;
  }

  /** True once something has written to the {@link #epilogue()}. */
  public boolean hasEpilogue() {
    return epilogue != null;
  }

  /**
   * Writer for content after the closing namespace brace — std::hash specializations must live at
   * global scope. Shares this file's include container; rendered in write order, so per-type
   * emissions land in definition order (a nested type's hash is declared before an outer type's
   * operator() uses it).
   */
  public CppWriter epilogue() {
    if (epilogue == null) {
      epilogue = new CppWriter(getImportContainer(), filename, cppNamespace);
    }
    return epilogue;
  }

  /** Factory used by the writer delegator. */
  public static final class Factory implements SymbolWriter.Factory<CppWriter> {
    private final CppSettings settings;

    public Factory(CppSettings settings) {
      this.settings = settings;
    }

    @Override
    public CppWriter apply(String filename, String namespace) {
      return new CppWriter(filename, settings.namespace());
    }
  }

  /** Records an include in angle ({@code <vector>}) or quote ({@code "opal/x.h"}) form. */
  public CppWriter addInclude(String include) {
    getImportContainer().add(include);
    return this;
  }

  /** Records every header a symbol needs. */
  public CppWriter addIncludesFor(Symbol symbol) {
    CppSymbolProvider.headersOf(symbol).forEach(this::addInclude);
    return this;
  }

  private boolean isCppSource() {
    return filename.endsWith(".h") || filename.endsWith(".cc");
  }

  @Override
  public String toString() {
    if (!isCppSource()) {
      return super.toString();
    }
    boolean isHeader = filename.endsWith(".h");
    StringBuilder out = new StringBuilder();
    out.append("// Code generated by smithy-cpp (cpp-codegen). DO NOT EDIT.\n\n");
    if (isHeader) {
      out.append("#ifndef ").append(includeGuard()).append('\n');
      out.append("#define ").append(includeGuard()).append("\n\n");
    }
    String includes = getImportContainer().render(filename);
    if (!includes.isEmpty()) {
      out.append(includes).append('\n');
    }
    out.append("namespace ").append(cppNamespace).append(" {\n\n");
    String body = super.toString();
    if (!isHeader && body.contains("types::")) {
      // Generated sources reference model types as types::X where a bare name
      // could be shadowed by a same-named file-local helper (issue #71); the
      // alias only appears in files that use it.
      out.append("namespace types = ::").append(cppNamespace).append(";\n\n");
    }
    out.append(body);
    if (!body.endsWith("\n")) {
      out.append('\n');
    }
    out.append("}  // namespace ").append(cppNamespace).append('\n');
    String extra = epilogue == null ? "" : epilogue.body().stripTrailing();
    if (!extra.isEmpty()) {
      out.append('\n').append(extra).append('\n');
    }
    if (isHeader) {
      out.append("\n#endif  // ").append(includeGuard()).append('\n');
    }
    return out.toString();
  }

  /**
   * Traditional include guard from the include-relative path ({@code include/example/weather/
   * types.h} → {@code EXAMPLE_WEATHER_TYPES_H_}), mirroring the runtime's hand-written convention.
   * Not {@code #pragma once}: toolchains with header validation (parse_headers) compile each header
   * standalone, and gcc unconditionally warns "#pragma once in main file" there — an unfixable
   * warning under the CI builds' -Werror.
   */
  private String includeGuard() {
    String path = filename.startsWith("/") ? filename.substring(1) : filename;
    if (path.startsWith("include/")) {
      path = path.substring("include/".length());
    }
    StringBuilder guard = new StringBuilder(path.length() + 1);
    for (int i = 0; i < path.length(); i++) {
      char c = path.charAt(i);
      guard.append(Character.isLetterOrDigit(c) ? Character.toUpperCase(c) : '_');
    }
    return guard.append('_').toString();
  }

  private String body() {
    return super.toString();
  }

  /** Include set with deterministic rendering. */
  public static final class IncludeContainer
      implements software.amazon.smithy.codegen.core.ImportContainer {

    private final Set<String> angle = new TreeSet<>();
    private final Set<String> quoted = new TreeSet<>();

    void add(String include) {
      if (include.startsWith("<")) {
        angle.add(include);
      } else {
        quoted.add(include);
      }
    }

    String render(String filename) {
      StringBuilder out = new StringBuilder();
      for (String include : angle) {
        out.append("#include ").append(include).append('\n');
      }
      boolean wroteQuoted = false;
      for (String include : quoted) {
        // The file being generated never includes itself.
        if (filename.endsWith(include.replace("\"", ""))) {
          continue;
        }
        if (!wroteQuoted && !angle.isEmpty()) {
          out.append('\n');
        }
        wroteQuoted = true;
        out.append("#include ").append(include).append('\n');
      }
      return out.toString();
    }

    @Override
    public void importSymbol(Symbol symbol, String alias) {
      CppSymbolProvider.headersOf(symbol).forEach(this::add);
    }
  }
}
