package io.smithycpp.codegen;

/** Emits tests/BUILD.bazel for a generated module (buildifier-clean). */
final class TestsBuildFileGenerator {

  private TestsBuildFileGenerator() {}

  static void run(
      CppContext context,
      boolean hasProtocolTests,
      boolean hasMalformedTests,
      boolean hasIntegrationTests) {
    String module = context.settings().testsPackage();
    String runtime = context.settings().runtimePackage();
    StringBuilder out = new StringBuilder();
    out.append(
        """
        # Code generated by opal-cpp (cpp-codegen). DO NOT EDIT.

        load("@rules_cc//cc:defs.bzl", "cc_test")

        cc_test(
            name = "smoke_test",
            size = "small",
            srcs = ["smoke_test.cc"],
            copts = [
                "-Wall",
                "-Wextra",
            ],
            deps = [
                "%s:client",
                "%s:server",
                "%s:client",
                "%s:http",
                "@googletest//:gtest_main",
            ],
        )
        """
            .formatted(module, module, runtime, runtime));
    if (hasProtocolTests) {
      for (String kind : new String[] {"request", "response"}) {
        out.append(
            """

            cc_test(
                name = "%s_tests",
                size = "small",
                srcs = ["%s_tests.cc"],
                copts = [
                    "-Wall",
                    "-Wextra",
                ],
                deps = [
                    "%s:client",
                    "%s:protocol_test_support",
                    "@googletest//:gtest_main",
                ],
            )
            """
                .formatted(kind, kind, module, runtime));
      }
      for (String kind : new String[] {"server_request", "server_response"}) {
        out.append(
            """

            cc_test(
                name = "%s_tests",
                size = "small",
                srcs = ["%s_tests.cc"],
                copts = [
                    "-Wall",
                    "-Wextra",
                ],
                deps = [
                    "%s:client",
                    "%s:server",
                    "%s:protocol_test_support",
                    "@googletest//:gtest_main",
                ],
            )
            """
                .formatted(kind, kind, module, module, runtime));
      }
    }
    if (hasMalformedTests) {
      out.append(
          """

          cc_test(
              name = "server_malformed_tests",
              size = "small",
              srcs = ["server_malformed_tests.cc"],
              copts = [
                  "-Wall",
                  "-Wextra",
              ],
              deps = [
                  "%s:client",
                  "%s:server",
                  "%s:protocol_test_support",
                  "@googletest//:gtest_main",
              ],
          )
          """
              .formatted(module, module, runtime));
    }
    if (hasIntegrationTests) {
      out.append(
          """

          cc_test(
              name = "integration_test",
              size = "small",
              srcs = ["integration_test.cc"],
              copts = [
                  "-Wall",
                  "-Wextra",
              ],
              deps = [
                  "%s:client",
                  "%s:server",
                  "%s:http",
                  "%s:protocol_test_support",
                  "@googletest//:gtest_main",
              ],
          )
          """
              .formatted(module, module, runtime, runtime));
    }
    context.fileManifest().writeFile("tests/BUILD.bazel", out.toString());
  }
}
